language: cpp

addons:
  apt:
    packages:
      - make
      - gcc-arm-none-eabi
      - binutils-arm-none-eabi
      - zip

env:
  global:
    - RASPPI=3

script:
  - arm-none-eabi-gcc --version
  - make RASPPI=3
  - test -f kernel.img

before_deploy:
  - zip kernel-pi1551-rpi3.zip kernel.img
  - echo Add deploy in 'deploy' block
